//
// Created by luca on 7/12/21.
//

#ifndef POWERMCU_PINS_H
#define POWERMCU_PINS_H
#define SOFTLATCH_OUTPUT_PIN GPIO_NUM_2
#define SOFTLATCH_BTN_PIN GPIO_NUM_27
#define SOFTLATCH_TOUCH_WAKEUP_PIN T7
#define LEDRING_PIN GPIO_NUM_18
#endif //POWERMCU_PINS_H
